### ISSUE TITLE
Class Index to Class Name Map

### ISSUE THREAD

**Issue by mclarkturner17** [RIVeR-Lab/hyper_drive_data#1]
Do you provide the class index to label name map used for the ATLAS annotation anywhere. I cannot find it.

**Comment by nhanson2** [comment]
The original ATLAS label paper is available here: http://gvsets.ndia-mich.org/documents/AAIR/2022/ATLAS,%20an%20All-Terrain%20Labelset%20for%20Autonomous%20Systems.pdf

It looks like the label map isn't in the repository for some reason. I'll work on adding it in tomorrow. Thanks for bringing this to my attention.

**Comment by nhanson2** [comment]
@mclarkturner17 I apologize for the delay. I've uploaded the label map and updated the instructions on the website with details on how to use. 

Quick Link: https://github.com/RIVeR-Lab/hyper_drive_data/blob/main/label_map.json

Feel free to open a new issue if you have problems using the mapping!
